### ISSUE TITLE
Difficulty Building Documentation

### ISSUE THREAD

**Issue by sdrucker4** [charles-sharman/ccad#12]
I'm on a windows 10 system and am not sure how to access or build documentation. 
ccad works great so far! using anaconda to handle the libraries.

While I know these should be separate issue tickets,,,

- do you know whether pythoncc / ccad works with miniconda?
- is there a parasolid save/export command in ccad? 
- do you know how to call anaconda from within a python script rather than having to type "python" into command line before executing?

thanks! 
Sam

**Comment by charles-sharman** [comment]
Hi Sam,

I'm glad you're enjoying ccad.  Before you get too far, check out Issue #11.  ccad has issues with the latest/greatest OCE/pythonocc.

The html documentation can be found at ccad/doc/html/contents.html, where ccad is where you installed ccad.  It's built with [Sphinx](http://www.sphinx-doc.org).  Once you've installed Sphinx, you can build the documentation with 

sphinx-build -b html sourcedir builddir

where sourcedir is ccad/doc.

I don't know anything about anaconda or miniconda, which unsatisfactorily answers your first and third bullet.  No, there is currently no parasolid save/export.  If the latest/greatest OCE/pythonocc supports it, however, it should be easy to add to ccad.  You could use the to_stl, to_step, and to_iges routines as templates.

**Comment by sdrucker4** [comment]
Charles,

Thank you for the speedy & comprehensive reply, I have since been able to build and use ccad's documentation- feel free to close the issue.

-sam

**Comment by charles-sharman** [comment]
Sam, I'm glad you could build the documentation.  I'll close the issue.

- Charles
