### ISSUE TITLE
port to coming pythonocc-0.16.0

### ISSUE THREAD

**Issue by tpaviot** [charles-sharman/ccad#7]
A new pythonocc release is coming. It introduces some api changes:

* some oce/occt method may require new arguments,

* it is strict regarding the difference between integers and bools (not possible anymore to pass 0 or 1 if the method expects True or False),

* static functions names moves to lowercase.

The branch https://github.com/charles-sharman/ccad/tree/tp/pythonocc-0.16-port fixes so that ccad is 0.16.0 ready.

Successfully tested on osx. All unittests pass.

**Comment by charles-sharman** [comment]
See my comments under Issue #8.  The master branch now contains the fixes from tp/pythonocc-0.16-port, and it fixes the display errors under Linux.
