### ISSUE TITLE
py3 support

### ISSUE THREAD

**Issue by tpaviot** [charles-sharman/ccad#8]
So far, ccad is py2 only compliant.

Branch tp/py3-port provides fixes to support both py2 and py3. 

Successfully tested on osx, with python-2.7.5 and python-3.4.0. All unittests pass on both pythons.

Note that this branch is based upon tp/pythonocc-0.16-port.

**Comment by charles-sharman** [comment]
I installed pythonocc-0.16, worked with tp/py3-port, made some modifications to get display working, and merged it into the master branch.  To my knowledge, the master branch is now python2 and python3 compliant, works with pythonocc-0.16, and is the most up-to-date.  Please make future modifications on that branch.  I'll remove tp/pythonocc-0.16-port and tp/py3-port soon.  Thanks for your help.
